from rl.envs.gym_envs.color_mix_env_3d import ColorMix3D
from rl.envs.gym_envs.color_mix_env_3d_7_fluids import ColorMix3D7Fluid
from rl.envs.gym_envs.color_mix_env_3d_14_fluids import ColorMix3D14Fluid
from rl.envs.gym_envs.color_mix_real_env_3d import ColorMixReal3D
from rl.envs.gym_envs.color_mix_env_3d_saturation import ColorMix3DSaturation
from rl.envs.gym_envs.color_mix_env_3d_saturation_7fluids import ColorMix3DSaturation7Fluids
from rl.envs.gym_envs.color_mix_env_3d_saturation_14fluids import ColorMix3DSaturation14Fluids
from rl.envs.gym_envs.color_mix_env_3d_continuous import ColorMix3DContinuous
